spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transfer?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useOldAliasMetadataBehavior=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1q2w3e4r!@
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case:  true

